:DOC-CONFIG:
#+property: header-args:emacs-lisp :tangle config.el :mkdirp yes :comments no
#+startup: fold
:END:
* Guidance
 Whenever you reconfigure a package, make sure to wrap your config in an
 `after!' block, otherwise Doom's defaults may override your settings. E.g.

   (after! PACKAGE
     (setq x y))

 The exceptions to this rule:

   - Setting file/directory variables (like `org-directory')
   - Setting variables which explicitly tell you to set them before their
     package is loaded (see 'C-h v VARIABLE' to look up their documentation).
   - Setting doom variables (which start with 'doom-' or '+').

 Here are some additional functions/macros that will help you configure Doom.

 - `load!' for loading external *.el files relative to this one
 - `use-package!' for configuring packages
 - `after!' for running code after a package has loaded
 - `add-load-path!' for adding directories to the `load-path', relative to
   this file. Emacs searches the `load-path' when you load packages with
   `require' or `use-package'.
 - `map!' for binding new keys

 To get information about any of these functions/macros, move the cursor over
 the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
 This will open documentation for it, including demos of how they are used.
 Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
 etc).

 You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
 they are implemented.

* Automatic config
** Environment variables
#+begin_src emacs-lisp :tangle yes
(use-package! dotenv
  :config
  ;; Load .env from ~/code/github.com/dotfiles/.env on startup
  (dotenv-update-project-env "~/code/github.com/dotfiles/")

  (add-hook 'projectile-after-switch-project-hook
            (lambda ()
              "Loading project-specific .env..."
              (dotenv-update-project-env (projectile-project-root)))))
#+end_src

*** Confirm the envars are being loaded
#+begin_src emacs-lisp
;; (getenv "GROQ_API_KEY")
#+end_src

** Coding
*** Lsp
#+begin_src emacs-lisp :tangle yes
(add-hook! 'java-mode #'lsp)
(add-hook! 'lsp-mode-hook #'lsp-lens-mode)
(add-hook! 'java-mode-hook #'lsp-java-boot-lens-mode)
#+end_src

*** Debugging

#+begin_src emacs-lisp :tangle yes
(map! :leader "d t" #'dap-breakpoint-toggle :desc "Debugger toggle breakpoint")
(map! :leader "d s" #'dap-debug :desc "Debugger start")
(map! :leader "d r" #'dap-debug-restart :desc "Debugger restart")
(map! :leader "d j" #'dap-java-debug-test-class :desc "Debug JUnit test")
(map! :leader "d d" #'dap-disconnect :desc "Debugger disconnect")
(map! :leader "d n" #'dap-next :desc "Debugger next")
(map! :leader "d o" #'dap-step-out :desc "Debugger step over")
(map! :leader "d i" #'dap-step-in :desc "Debugger step in")
(map! :leader "d l" #'dap-locals :desc "Debugger locals")
(map! :leader "d e a" #'dap-ui-expressions-add :desc "Debugger Expression Add")
(map! :leader "d e l" #'dap-ui-expressions :desc "Debugger Expression list")
(map! :leader "d e r" #'dap-ui-expressions-remove :desc "Debugger Expression Remove")
(map! :leader "d b b" #'dap-ui-breakpoints-browse :desc "Debugger Breakpoints Browse")
(map! :leader "d b c" #'dap-breakpoint-delete-all :desc "Debugger Breakpoint Clear")
#+end_src

** Eshell
#+begin_src emacs-lisp :tangle yes
(add-hook! 'eshell-first-time-mode-hook
           (eshell/alias "jenv" "~/.jenv/bin/jenv $*"))
#+end_src
** Theme settings
*** Theme color scheme
#+begin_src emacs-lisp :tangle yes
(setq doom-theme 'doom-one)
#+end_src

*** Display line numbers
#+begin_src emacs-lisp :tangle yes
(setq display-line-numbers-type 'relative)
#+end_src
*** Default window size
#+begin_src emacs-lisp :tangle yes
(modify-frame-parameters nil '((undecorated . t) (skip-taskbar . t)))
#+end_src

#+RESULTS:

** Emacs everywhere

#+begin_src emacs-lisp :tangle yes
(setq emacs-everywhere-frame-parameters
      '((width . 80)        ;; ~600px)
        (height . 15)       ;; 15 characters tall
        (undecorated . t)   ;; remove title bar
        (skip-taskbar . t)  ;; do not show in taskbar
        (vertical-scroll-bars . nil)
        (horizontal-scroll-bars . nil)))
#+end_src

#+RESULTS:
: ((width . 80) (height . 15) (undecorated . t) (skip-taskbar . t) (vertical-scroll-bars) (horizontal-scroll-bars))

** Org mode settings
*** General
#+begin_src emacs-lisp :tangle yes
(setq org-directory "~/org/")
#+end_src
*** Keymaps
#+begin_src emacs-lisp :tangle yes
(map! :leader (:prefix "t" :desc "[T]angle [O]rg file" "o" 'org-babel-tangle))
#+end_src

#+RESULTS:
: org-babel-tangle

** Music
*** eradio
**** Startup
This autoplays the radio when emacs starts up for the first time.
#+begin_src emacs-lisp :tangle yes
(eradio-play "https://somafm.com/bossa256.pls")
#+end_src

**** Keymaps
#+begin_src emacs-lisp :tangle yes
(map! :leader (:prefix ("r" . "eradio") :desc "Play a radio channel" "p" 'eradio-play))
(map! :leader (:prefix ("r" . "eradio") :desc "Stop the radio player" "s" 'eradio-stop))
(map! :leader (:prefix ("r" . "eradio") :desc "Toggle the radio player" "t" 'eradio-toggle))
#+end_src

**** Radio list
#+begin_src emacs-lisp :tangle yes
(setq eradio-channels '(("def con - soma fm" . "https://somafm.com/defcon256.pls")         ;; electronica with defcon-speaker bumpers
                        ("metal - soma fm"   . "https://somafm.com/metal130.pls")          ;; \m/
                        ("bossa beyond - soma fm"  . "https://somafm.com/bossa256.pls")    ;; bossa nova
                        ("ambient - soma fm"  . "https://somafm.com/groovesalad256.pls")   ;; ambient and chill
                        ("specials - soma fm"  . "https://somafm.com/nossl/specials.pls")   ;; Soma fm specials, mixed
                        ))
#+end_src

** Web search
Leverages =counsel-web-search= to open a mini-buffer at the bottom of the screen, showing the top results of the search

#+begin_src emacs-lisp :tangle yes
(map! :leader "s w" 'eww :desc "Search the web")
(setq eww-auto-rename-buffer 'title)
(setq eww-buffers-queryable nil)
#+end_src
*** Docs
#+begin_src emacs-lisp :tangle yes
(map! :leader "s d" 'devdocs-lookup :desc "Search offline docs")
#+end_src
** AI
*** gptel
#+begin_src emacs-lisp :tangle yes
(use-package! gptel)
(setq gptel-default-mode 'org-mode)
(setq gptel-model 'llama-3.3-70b-versatile
      gptel-backend
      (gptel-make-openai "Groq"
        :host "api.groq.com"
        :endpoint "/openai/v1/chat/completions"
        :stream t
        :key (getenv "GROQ_API_KEY") ;can be a function that returns the key
        :models '(llama-3.3-70b-versatile
                  llama-3.1-8b-instant
                  llama3-70b-8192
                  llama3-8b-8192
                  mixtral-8x7b-32768
                  gemma-7b-it)))
#+end_src

** Discord
*** Startup
Install package to share status in emacs using Discord Rich Presence
#+begin_src emacs-lisp :tangle yes
(setq elcord-editor-icon "emacs_material_icon")
(elcord-mode 1)
#+end_src

* Manual execution
** Swapping caps for escape
This needs to be done in $HOME/.profile: =/usr/bin/setxkbmap -option "caps:swapescape"=
Or C-c C-c in the code block below:
#+begin_src bash
echo /usr/bin/setxkbmap -option "caps:swapescape" >> $HOME/.profile
#+end_src

Alternatively, set up the startup application in your Distro settings:
#+begin_src bash
/usr/bin/setxkbmap -option "caps:swapescape"
#+end_src

** Emacs everywhere
This needs to be set to a keybind in your system
#+begin_src bash
emacsclient --eval "(emacs-everywhere)"
#+end_src

#+RESULTS:
