#!/bin/bash

sudo apt update
sudo apt upgrade
sudo apt install ripgrep xclip cmake gcc python3 python3-pip libtool libtool-bin xdotool vlc nodejs npm mu4e maildir-utils pandoc anki

# Doom Emacs
if ! type emacs; then
    sudo apt install emacs
    git clone --depth 1 https://github.com/doomemacs/doomemacs ~/.config/emacs
    ~/.config/emacs/bin/doom install
fi

# Java
if ! type java; then
  echo "Installing java 25..."
  wget https://download.oracle.com/java/25/latest/jdk-25_linux-x64_bin.tar.gz
  tar xvf jdk-25_linux-x64_bin.tar.gz
  sudo mv jdk-25 /opt/
  rm -rf jdk-25_linux-x64_bin.tar.gz
  echo "java 25 installed!"

  echo "Installing java 21..."
  wget https://download.oracle.com/java/21/archive/jdk-21.0.7_linux-x64_bin.tar.gz
  tar xvf jdk-21.0.7_linux-x64_bin.tar.gz
  sudo mv jdk-21.0.7 /opt/
  rm -rf jdk-21.0.7_linux-x64_bin.tar.gz
  echo "java 21 installed!"
fi

# Install Java version manager
if ! type jenv; then
  echo "Installing jenv..."
  git clone https://github.com/jenv/jenv.git ~/.jenv
  echo "jenv installed!"

  echo "setting up java versions on jenv..."
  jenv add /opt/jdk-21.0.7/
  jenv add /opt/jdk-25/
fi
# Create symlinks
current_directory=$(pwd)
echo "Removing existing config files"
rm -rf $HOME/.config/doom

echo "Creating sym links..."
ln -sf $current_directory/doom $HOME/.config/doom
echo "Sym links created!"

$HOME/.config/emacs/bin/doom sync

echo "Create example .env file"
mv .env-example .env
